name: Auto Update Packages

on:
  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: ubuntu-latest
    secrets:
      TOKEN:
        required: true

jobs:
  auto-update:
    name: Auto Update
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: write
      packages: write
    
    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.head_ref }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Add GitHub NuGet Source
      run: dotnet nuget add source https://nuget.pkg.github.com/ServerEmus/index.json --name "github" --username "any" --password ${{ secrets.GITHUB_TOKEN  }} --store-password-in-clear-text

    - name: Install outdated tool
      run: dotnet tool install --global dotnet-outdated-tool
      
    - name: Run tool
      continue-on-error: true
      id: run-tool
      run: |
          mkdir Out
          dotnet outdated -o:Out/Outdate.md -of:markdown -f

    - name : Upload
      uses: actions/upload-artifact@v5
      with:
        name: OutMD
        path: Out
        
    - name: Update packages and test
      id: update-test
      if: steps.run-tool.outcome == 'failure'
      run: |
        dotnet outdated -u
        dotnet build
        dotnet test

    - uses: stefanzweifel/git-auto-commit-action@v7
      if: steps.update-test.outcome != 'failure'
      with:
        commit_message: "Upgraded nuget dependencies!"