name: Publish Package

on:
  workflow_call:
    inputs:
      ProjName:
        required: true
        type: string
      PackagePrefix:
        required: false
        type: string
        default: ServerEmus.
      runner:
        required: false
        type: string
        default: ubuntu-latest
    secrets:
      TOKEN:
        required: true

jobs:
  publish:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v5
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Add GitHub NuGet Source
      run: dotnet nuget add source https://nuget.pkg.github.com/ServerEmus/index.json --name "github" --username "any" --password ${{ secrets.TOKEN  }} --store-password-in-clear-text

    - name: Build
      run: dotnet build ${{ inputs.ProjName }}/${{ inputs.ProjName }}.csproj -o Out

    - name: Publish to GitHub Packages
      run: dotnet nuget push Out/${{ inputs.PackagePrefix }}${{ inputs.ProjName }}**.nupkg --source "github" --api-key ${{ secrets.TOKEN  }}

    - name : Upload
      uses: actions/upload-artifact@v5
      with:
        name: ${{ inputs.ProjName }}
        path: Out/${{ inputs.PackagePrefix }}${{ inputs.ProjName }}**.nupkg

    - name: Release
      uses: softprops/action-gh-release@v2.4.2
      with:
        files: Out/${{ inputs.PackagePrefix }}${{ inputs.ProjName }}**.nupkg

