name: Pre Release

on:
  workflow_call:
    inputs:
      ProjName:
        required: true
        type: string
      runner:
        required: false
        type: string
        default: windows-latest
      uploadName:
        required: false
        type: string
    secrets:
      TOKEN:
        required: true

jobs:
  prerelease:
    name: PreRelease
    runs-on: ${{ inputs.runner }}
    permissions:
      packages: read
      contents: write

    steps:
    - uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Add GitHub NuGet Source
      run: dotnet nuget add source https://nuget.pkg.github.com/ServerEmus/index.json --name "github" --username "any" --password ${{ secrets.TOKEN }} --store-password-in-clear-text

    - name: Build
      run: dotnet build ${{ inputs.ProjName }}/${{ inputs.ProjName }}.csproj -o Out

    - name: Run test
      run: dotnet test

    - name : Upload
      uses: actions/upload-artifact@v5
      with:
        name: ${{ inputs.uploadName || inputs.ProjName }}
        path: Out/*

    - name: Create zip archive
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: 'Prerelease.zip'
        path: Out

    - name: Release
      uses: softprops/action-gh-release@v2.4.2
      with:
        token: ${{ secrets.TOKEN }}
        prerelease: True
        files: Prerelease.zip
        tag_name: prerelease
